controller_list:
  - name: fake_manipulator_controller
    joints:
      - $(arg prefix)shoulder_pan_joint
      - $(arg prefix)shoulder_lift_joint
      - $(arg prefix)elbow_joint
      - $(arg prefix)wrist_1_joint
      - $(arg prefix)wrist_2_joint
      - $(arg prefix)wrist_3_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home
